spring:
  application:
    name: demo
security:
  oauth2:
    client:
      clientId: 854502805785-8suj2rjlqcbs4sppqmh24kkjr5nb6luc.apps.googleusercontent.com
      clientSecret: u8xDHCdb-5l333SWiVydlxzv
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
