spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demonbaza
    username: 'root'
    password:
  jpa:
    jpa.hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true